#ifndef PINS_H
#define PINS_H

#include <avr/io.h>

#define STEPPERS_SEL_EN_DDR DDRD
#define STEPPERS_SEL_EN_PORT PORTD
#define STEPPERS_SEL_EN_PIN PD7

#define STEPPERS_SEL_DIR_DDR DDRB
#define STEPPERS_SEL_DIR_PORT PORTB
#define STEPPERS_SEL_DIR_PIN PB0

#define STEPPERS_SEL_STEP_DDR DDRD
#define STEPPERS_SEL_STEP_PORT PORTD
#define STEPPERS_SEL_STEP_PIN PD6 //OC0A

#define STEPPERS_DIS_EN_DDR DDRD
#define STEPPERS_DIS_EN_PORT PORTD
#define STEPPERS_DIS_EN_PIN PD4

#define STEPPERS_DIS_DIR_DDR DDRB
#define STEPPERS_DIS_DIR_PORT PORTB
#define STEPPERS_DIS_DIR_PIN PB1

#define STEPPERS_DIS_STEP_DDR DDRB
#define STEPPERS_DIS_STEP_PORT PORTB
#define STEPPERS_DIS_STEP_PIN PB3 //OC2A

#define SEL_IR_DDR DDRD
#define SEL_IR_PIN_REG PIND
#define SEL_IR_PIN PD3 //INT1

//LS = limit switch
#define DIS_LS_DDR DDRD
#define DIS_LS_PIN_REG PIND
#define DIS_LS_PORT PORTD
#define DIS_LS_PIN PD2 //INT0

#define DIS_IR_DDR DDRB
#define DIS_IR_PIN_REG PINB
#define DIS_IR_PORT PORTB
#define DIS_IR_PIN PB2 //PCINT2

#endif

