#ifndef PINS_H
#define PINS_H

#include <avr/io.h>

#define STEPPERS_SEL_EN_DDR DDRD
#define STEPPERS_SEL_EN_PORT PORTD
#define STEPPERS_SEL_EN_PIN PD7

#define STEPPERS_SEL_DIR_DDR DDRD
#define STEPPERS_SEL_DIR_PORT PORTD
#define STEPPERS_SEL_DIR_PIN PD5

#define STEPPERS_SEL_STEP_DDR DDRD
#define STEPPERS_SEL_STEP_PORT PORTD
#define STEPPERS_SEL_STEP_PIN PD6 //OC0A

#define STEPPERS_DIS_EN_DDR DDRB
#define STEPPERS_DIS_EN_PORT PORTB
#define STEPPERS_DIS_EN_PIN PB0

#define STEPPERS_DIS_DIR_DDR DDRB
#define STEPPERS_DIS_DIR_PORT PORTB
#define STEPPERS_DIS_DIR_PIN PB1

#define STEPPERS_DIS_STEP_DDR DDRD
#define STEPPERS_DIS_STEP_PORT PORTD
#define STEPPERS_DIS_STEP_PIN PD3 //OC2B

#define SEL_IR_DDR DDRC
#define SEL_IR_PIN_REG PINC
#define SEL_IR_PIN PC2 //PCINT10

#define DIS_LS_DDR DDRD
#define DIS_LS_PIN_REG PIND
#define DIS_LS_PORT PORTD
#define DIS_LS_PIN PD2 //INT0

#define DIS_IR_DDR DDRC
#define DIS_IR_PIN_REG PINC
#define DIS_IR_PORT PORTC
#define DIS_IR_PIN PC3

#define LED_DDR DDRC
#define LED_PORT PORTC
#define LED_PIN PC0

#endif

